@url=http://localhost:3000

###Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "juancito@gmail.com" ,
    "password": "contraseña123"
}

### POST de turno
POST {{url}}/turnos
Content-Type: application/json

{
    "paciente_id": 2,
    "medico_id": 1,
    "fecha": "2024-12-15", 
    "hora": "16:30",
    "estado": "pendiente",
    "observaciones": "El paciente es medio medio" 
}

Authorization: Bearer {{token}}
###
@token = {{login.response.body.token}}

###
PUT {{url}}/turnos/9
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "paciente_id": 2,
    "medico_id": 1,
    "fecha": "2024-11-20", 
    "hora": "16:30",
    "estado": "Pendiente",
    "observaciones": "Esta gaga" 
}

### POST de turno
POST {{url}}/turnos
Content-Type: application/json

{
    "paciente_id": 2,
    "medico_id": 1,
    "fecha": "2024-12-15", 
    "hora": "16:30",
    "estado": "pendiente",
    "observaciones": "El paciente es medio medio" 
}

Authorization: Bearer {{token}}

###GET medicos

GET {{url}}/turnos/9/info
Authorization: Bearer {{token}}

###GET turnos
GET {{url}}/turnos
Authorization: Bearer {{token}}

###GET pacientes
GET {{url}}/pacientes
Authorization: Bearer {{token}}

###POST medico

POST {{url}}/medicos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Nazareno",
    "apellido": "Mansilla",
    "especialidad": "Pediatria",
    "matricula_profesional": "3445546465"
}

### POST de paciente
POST {{url}}/pacientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Dario",
    "apellido": "Mansilla",
    "dni": "4546545",
    "fecha_nacimiento": "1969-12-20",
    "obra_social": "OSDE"
}